name:                chinesechess
version:             0.1.0.0
github:              "githubuser/chinesechess"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/chinesechess#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal >= 0.8.0.2 && < 0.9
- mtl >= 2.2.2 && < 2.3
- transformers >= 0.5.2.0 && < 0.6
- transformers-either >= 0.0.2 && < 0.1
- random >= 1.1 && < 1.2

library:
  source-dirs: src
  default-extensions:
  - FlexibleContexts
  - FlexibleInstances
  - ConstraintKinds

executables:
  chinesechess-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chinesechess

tests:
  chinesechess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chinesechess
